name: dokan_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #use for bottom navigation bar
  animated_bottom_navigation_bar: ^1.3.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # use for routing
  go_router: ^14.1.4
  # use for responsive design
  flutter_screenutil: ^5.9.3
  # use for simple state update
  flutter_hooks: ^0.20.5
  #local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # use for networking
  dio: ^5.4.3+1

  # use for functional programming
  dartz: ^0.10.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #state management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  injectable: ^2.4.2
  get_it:

  #use for HTML parse
  flutter_widget_from_html: ^0.15.0

  # use for native splash builder
  flutter_native_splash: ^2.4.0

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

  injectable_generator:

  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

